[package]
name = "MockFlashLoan"
version = "0.0.0"

[addresses]
deployer = "_"

[dev-addresses]
deployer = "0x42"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "v1.2.0" }
