/**
 * frontend/lib/bot-constant.ts
 *
 * Env-config shape and defaults for all bot archetypes generated by the
 * Meta-Agent. Every key that any generated bot might need is listed here so
 * the UI can render the correct input fields dynamically.
 */

// ─── Intent shape returned by the orchestrator ────────────────────────────────

export interface BotIntent {
  chain?:                  "evm" | "solana" | "initia";
  network?:                string;
  execution_model?:        "polling" | "websocket" | "agentic";
  strategy?:               string;
  mcps?:                   string[];
  bot_name?:               string;
  requires_openai?:        boolean;

  // Legacy keys kept for backward compatibility with existing records/routes.
  required_mcps?:          string[];
  bot_type?:               string;
  requires_openai_key?:    boolean;
  requires_solana_wallet?: boolean;
}

// ─── Full env config — superset of every possible bot requirement ─────────────

export interface BotEnvConfig {
  // ── Core (present for every bot) ───────────────────────────────────────────
  SIMULATION_MODE:     string;   // "true" | "false"
  MCP_GATEWAY_URL:     string;   // e.g. "http://192.168.1.50:8000/mcp"

  // ── EVM wallet ─────────────────────────────────────────────────────────────
  RPC_PROVIDER_URL:    string;   // e.g. https://base-sepolia.g.alchemy.com/v2/...
  WALLET_PRIVATE_KEY:  string;   // 64-char hex

  // ── Solana wallet ───────────────────────────────────────────────────────────
  SOLANA_RPC_URL:      string;   // e.g. https://mainnet.helius-rpc.com/?api-key=...
  SOLANA_PRIVATE_KEY:  string;   // bs58-encoded keypair secret

  // ── Initia wallet ───────────────────────────────────────────────────────────
  INITIA_KEY:          string;
  INITIA_RPC_URL:      string;

  // ── DEX / aggregator API keys ───────────────────────────────────────────────
  ONEINCH_API_KEY:     string;   // https://portal.1inch.dev
  ALCHEMY_API_KEY:     string;   // https://dashboard.alchemy.com

  // ── Security providers ──────────────────────────────────────────────────────
  WEBACY_API_KEY:      string;   // https://webacy.com
  GOPLUS_API_KEY:      string;   // https://gopluslabs.io

  // ── AI / agentic ────────────────────────────────────────────────────────────
  OPENAI_API_KEY:      string;   // https://platform.openai.com

  // ── Social / data ────────────────────────────────────────────────────────────
  LUNARCRUSH_API_KEY:  string;   // https://lunarcrush.com
  NANSEN_API_KEY:      string;   // https://nansen.ai
  SERUM_API_URL:       string;   // Solana market-data endpoint used by some arbitrage templates
  PYTH_NETWORK_API_KEY: string;  // https://pyth.network (if required by generated bot)
  PYTH_PRO_ACCESS_TOKEN: string; // Optional token for Pyth pro feeds

  // ── Bot tuning ───────────────────────────────────────────────────────────────
  BORROW_AMOUNT_HUMAN: string;   // Human-readable base-token borrow amount
  POLL_INTERVAL:       string;   // Seconds between cycles

  // Allow arbitrary extra keys (e.g. custom bot vars)
  [key: string]: string;
}

// ─── Defaults ────────────────────────────────────────────────────────────────

export const DEFAULT_BOT_ENV_CONFIG: BotEnvConfig = {
  SIMULATION_MODE:     "false",
  MCP_GATEWAY_URL:     "http://192.168.1.50:8000/mcp",

  RPC_PROVIDER_URL:    "",
  WALLET_PRIVATE_KEY:  "",

  SOLANA_RPC_URL:      "",
  SOLANA_PRIVATE_KEY:  "",

  INITIA_KEY:          "",
  INITIA_RPC_URL:      "",

  ONEINCH_API_KEY:     "",
  ALCHEMY_API_KEY:     "",

  WEBACY_API_KEY:      "",
  GOPLUS_API_KEY:      "",

  OPENAI_API_KEY:      "",

  LUNARCRUSH_API_KEY:  "",
  NANSEN_API_KEY:      "",
  SERUM_API_URL:       "",
  PYTH_NETWORK_API_KEY: "",
  PYTH_PRO_ACCESS_TOKEN: "",

  BORROW_AMOUNT_HUMAN: "1",
  POLL_INTERVAL:       "5",
};

// ─── Field definitions keyed by intent ───────────────────────────────────────

/**
 * Given a BotIntent, returns the ordered list of env-var keys the user must
 * (or may) supply.  The "always" group is always included first.
 */
export function getRequiredEnvFields(intent?: BotIntent | null): EnvFieldDef[] {
  const mcps = Array.from(new Set([
    ...((intent?.mcps ?? []).map((m) => String(m || "").trim()).filter(Boolean)),
    ...((intent?.required_mcps ?? []).map((m) => String(m || "").trim()).filter(Boolean)),
  ]));
  const chain = intent?.chain ?? "evm";
  const model = intent?.execution_model ?? "polling";
  const strategy = (intent?.strategy ?? "").toString().toLowerCase();
  const botType = (intent?.bot_name ?? intent?.bot_type ?? "").toString().toLowerCase();
  const requiresOpenAI = Boolean(intent?.requires_openai ?? intent?.requires_openai_key);

  const fields: EnvFieldDef[] = [
    // ── Always ────────────────────────────────────────────────────────────────
    {
      key:         "MCP_GATEWAY_URL",
      label:       "MCP Gateway URL",
      type:        "text",
      required:    true,
      placeholder: "http://192.168.1.50:8000/mcp",
      helpText:    "URL of the running Python Meta-Agent server (uvicorn main:app).",
    },
    {
      key:      "SIMULATION_MODE",
      label:    "Execution Mode",
      type:     "toggle",
      required: false,
      placeholder: "true",
      helpText: "Simulation logs opportunities without sending real transactions.",
    },
  ];

  if (chain === "initia") {
    fields.push(
      {
        key:         "INITIA_KEY",
        label:       "Initia Private Key",
        type:        "password",
        required:    true,
        placeholder: "0x...",
        helpText:    "Required for move_execute signing via Initia MCP.",
      },
      {
        key:         "INITIA_RPC_URL",
        label:       "Initia RPC URL (Optional)",
        type:        "text",
        required:    false,
        placeholder: "https://rpc.testnet.initia.xyz/",
        helpText:    "Optional override for Initia RPC endpoint.",
      },
    );
  }

  // ── EVM wallet ───────────────────────────────────────────────────────────
  if (chain === "evm") {
    fields.push(
      {
        key:         "RPC_PROVIDER_URL",
        label:       "EVM RPC URL",
        type:        "text",
        required:    !intent?.requires_solana_wallet,
        // liveOnly:    true, // removed
        placeholder: "https://base-sepolia.g.alchemy.com/v2/YOUR_KEY",
        helpText:    "Required for live mode. Free from Alchemy, Infura, or QuickNode.",
      },
      {
        key:         "WALLET_PRIVATE_KEY",
        label:       "Wallet Private Key",
        type:        "password",
        required:    true, // always required
        // liveOnly:    true, // removed
        placeholder: "64-char hex (no 0x prefix)",
        helpText:    "Required to initialize the wallet.",
      },
    );
  }

  // ── Solana wallet ────────────────────────────────────────────────────────
  if (chain === "solana" || intent?.requires_solana_wallet) {
    fields.push(
      {
        key:         "SOLANA_RPC_URL",
        label:       "Solana RPC URL",
        type:        "text",
        required:    true,
        placeholder: "https://mainnet.helius-rpc.com/?api-key=YOUR_KEY",
        helpText:    "Helius or QuickNode give the fastest Solana RPCs.",
        helpLink:    "https://helius.dev",
        helpLinkLabel: "Get Helius key →",
      },
      {
        key:         "SOLANA_PRIVATE_KEY",
        label:       "Solana Private Key (bs58)",
        type:        "password",
        required:    true, // always required
        // liveOnly:    true, // removed
        placeholder: "base58-encoded keypair secret",
        helpText:    "Export from Phantom: Settings → Export Private Key.",
      },
    );

    // Some Solana arbitrage templates rely on a Serum endpoint for market discovery.
    if (strategy.includes("arbitrage") || strategy.includes("flash")) {
      fields.push({
        key:          "SERUM_API_URL",
        label:        "Serum API URL",
        type:         "text",
        required:     true,
        placeholder:  "https://api.mainnet-beta.solana.com",
        helpText:     "Used by Solana arbitrage templates for market data routing.",
      });
    }
  }

  // ── 1inch ────────────────────────────────────────────────────────────────
  if (mcps.includes("one_inch") || mcps.includes("1inch")) {
    fields.push({
      key:          "ONEINCH_API_KEY",
      label:        "1inch API Key",
      type:         "password",
      required:     true,
      placeholder:  "your-1inch-api-key",
      helpText:     "Required for price quotes and swap calldata.",
      helpLink:     "https://portal.1inch.dev",
      helpLinkLabel: "Get key →",
    });
  }

  // ── Alchemy / mempool ─────────────────────────────────────────────────────
  if (mcps.includes("alchemy") || model === "websocket") {
    fields.push({
      key:          "ALCHEMY_API_KEY",
      label:        "Alchemy API Key",
      type:         "password",
      required:     model === "websocket",
      placeholder:  "your-alchemy-api-key",
      helpText:     "Required for WebSocket mempool streaming and enhanced RPC.",
      helpLink:     "https://dashboard.alchemy.com",
      helpLinkLabel: "Get key →",
    });
  }

  // ── Webacy ────────────────────────────────────────────────────────────────
  const needsWebacyByStrategy =
    chain !== "initia" && (
    strategy.includes("arbitrage") ||
    strategy.includes("flash") ||
    strategy.includes("mev") ||
    botType.includes("arbitrage") ||
    botType.includes("flash") ||
    botType.includes("mev")
    )

  const needsGoPlusByStrategy =
    chain !== "initia" && (
    strategy.includes("sentiment") ||
    strategy.includes("arbitrage") ||
    strategy.includes("flash") ||
    strategy.includes("mev") ||
    strategy.includes("sniper") ||
    botType.includes("sentiment") ||
    botType.includes("arbitrage") ||
    botType.includes("flash") ||
    botType.includes("mev") ||
    botType.includes("sniper")
    )

  if (mcps.includes("webacy") || needsWebacyByStrategy) {
    fields.push({
      key:          "WEBACY_API_KEY",
      label:        "Webacy API Key",
      type:         "password",
      required:     true,
      placeholder:  "your-webacy-api-key",
      helpText:     "Token risk scoring run before every trade execution.",
      helpLink:     "https://webacy.com",
      helpLinkLabel: "Get key →",
    });
  }

  // ── GoPlus ───────────────────────────────────────────────────────────────
  if (mcps.includes("goplus") || needsGoPlusByStrategy) {
    fields.push({
      key:          "GOPLUS_API_KEY",
      label:        "GoPlus API Key (Optional)",
      type:         "password",
      required:     false,
      placeholder:  "optional-for-public-endpoint",
      helpText:     "Optional. GoPlus public token security endpoint works without an API key.",
      helpLink:     "https://gopluslabs.io",
      helpLinkLabel: "Get key →",
    });
  }

  // ── OpenAI (agentic bots) ─────────────────────────────────────────────────
  if (requiresOpenAI || model === "agentic") {
    fields.push({
      key:          "OPENAI_API_KEY",
      label:        "OpenAI API Key",
      type:         "password",
      required:     true,
      placeholder:  "sk-...",
      helpText:     "Used by the sub-LLM to interpret signals and make trade decisions.",
      helpLink:     "https://platform.openai.com/api-keys",
      helpLinkLabel: "Get key →",
    });
  }

  // ── LunarCrush ───────────────────────────────────────────────────────────
  if (mcps.includes("lunarcrush")) {
    fields.push({
      key:          "LUNARCRUSH_API_KEY",
      label:        "LunarCrush API Key",
      type:         "password",
      required:     true,
      placeholder:  "your-lunarcrush-api-key",
      helpText:     "Social sentiment scores for crypto tokens.",
      helpLink:     "https://lunarcrush.com",
      helpLinkLabel: "Get key →",
    });
  }

  // ── Nansen ───────────────────────────────────────────────────────────────
  if (mcps.includes("nansen")) {
    fields.push({
      key:          "NANSEN_API_KEY",
      label:        "Nansen API Key",
      type:         "password",
      required:     true,
      placeholder:  "your-nansen-api-key",
      helpText:     "Smart money wallet intelligence and on-chain flow data.",
      helpLink:     "https://nansen.ai",
      helpLinkLabel: "Get key →",
    });
  }

  // ── Pyth ─────────────────────────────────────────────────────────────────
  if (mcps.includes("pyth")) {
    fields.push(
      {
        key:          "PYTH_NETWORK_API_KEY",
        label:        "Pyth Network API Key (Optional)",
        type:         "password",
        required:     false,
        placeholder:  "optional-for-public-feeds",
        helpText:     "Optional. Public Pyth feeds work without this key.",
        helpLink:     "https://www.pyth.network",
        helpLinkLabel: "Pyth docs →",
      },
      {
        key:          "PYTH_PRO_ACCESS_TOKEN",
        label:        "Pyth Pro Access Token (Optional)",
        type:         "password",
        required:     false,
        placeholder:  "optional-pro-token",
        helpText:     "Optional. Needed only for pro feeds such as equities/FX/metals.",
      },
    );
  }

  // ── Bot tuning (polling bots) ─────────────────────────────────────────────
  if (model === "polling" || !model) {
    fields.push(
      {
        key:         "BORROW_AMOUNT_HUMAN",
        label:       "Borrow Amount",
        type:        "text",
        required:    false,
        placeholder: "1",
        helpText:    "Human-readable token amount to borrow per flash-loan cycle.",
      },
      {
        key:         "POLL_INTERVAL",
        label:       "Poll Interval (seconds)",
        type:        "text",
        required:    false,
        placeholder: "5",
        helpText:    "Seconds between each arbitrage opportunity check.",
      },
    );
  }

  return fields;
}

// ─── Field definition type ────────────────────────────────────────────────────

export interface EnvFieldDef {
  key:           keyof BotEnvConfig;
  label:         string;
  type:          "text" | "password" | "toggle";
  required:      boolean;
  liveOnly?:     boolean;
  placeholder:   string;
  helpText?:     string;
  helpLink?:     string;
  helpLinkLabel?: string;
}

// ─── Legacy constants (kept for backward compatibility) ───────────────────────

export const BOT_ENTRY_POINT = "src/index.ts";

export const BOT_NPMRC = [
  "registry=https://registry.npmjs.org/",
  "maxsockets=2",
  "fetch-retries=5",
  "fetch-retry-mintimeout=20000",
  "fetch-retry-maxtimeout=120000",
  "fund=false",
  "audit=false",
].join("\n");